### ISSUE TITLE
Option to customize button text

### ISSUE THREAD

**Issue by qwertydude** [humanmade/Custom-Meta-Boxes#104]
I would like an option for repeatable fields etc to customize the button text. I have hacked CMB to do it, but would like it built in. 

It is a simple case of replacing "Add New" in button inputs with

`<?php echo esc_attr( $this->args['button'] ); ?>`

and adding a default for the 'button'  option.

Thanks

Chris

**Comment by mikeselander** [comment]
This is available to modify with the options:

```
'string-repeat-field' => 'My New Stuff',
'string-delete-field' => 'Delete Stuff',
```

I have updated the documentation appropriately.
