### ISSUE TITLE
Expand usability to options pages 

### ISSUE THREAD

**Issue by qwertydude** [humanmade/Custom-Meta-Boxes#108]
Having the core field creation in place, I was wondering if you'd consider expanding CMB to provide fields on options pages? It might not require too much work (famous last words), just needs a page creation and save engine for options...

**Comment by mikeselander** [comment]
This is a very cool feature, but not something that we're looking to support.

https://github.com/CMB2/CMB2 does support metaboxes on settings pages and would be worth looking into.
