### ISSUE TITLE
Taxonomies multiselect?

### ISSUE THREAD

**Issue by qwertydude** [humanmade/Custom-Meta-Boxes#150]
Hey Matthew

Can you add the ability for taxonomies etc to be multiselect?

Thanks

Chris

**Comment by sanchothefat** [comment]
@qwertydude we need to update the wiki but the select fields all extend the standard select type - this means you can pass in the options `multiple` and `allow_none` to the taxonomy select. Eg:

```php
add_filter( 'cmb_meta_boxes', function( array $meta_boxes ) {
  $fields = array(
    array(
      'id' => 'my_taxonomy',
      'name' => __( 'My Taxonomy' ),
      'type' => 'taxonomy_select',
      'multiple' => true
    )
  );

  $meta_boxes[] = array(
    'title' => __( 'Taxonomy' ),
    'fields' => $fields
  );

  return $meta_boxes;
} );
```

**Comment by sanchothefat** [comment]
Updated the wiki to reflect that this functionality already exists
