### ISSUE TITLE
Templates for meta boxes (Feature Request)

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#158]
- First of all thanks to gr8 people behind this amazing piece of code 
- Custom Meta Box is must have for wordpress developers & i just can't live without it
- Have used on many project which saved hours and also made the backend simple and easy
- Don't know if someone already mentioned this it will be good to have templating for meta box
- Some templates bundles based on common pattern or defining own template to display the meta box
- Like having meta boxes displayed in tabs or accordion (Specifying parameter in array like display type [flat/ tab / accordion] )
- Template for Individual meta boxes, often feel like have more control over how meta box is rendered apart from table layout 

Just a rough idea i had in mind so thought to share it !

**Comment by mikeselander** [comment]
@mattheu @ajitbohra this feels an awful lot like group fields to me, does this not solve the same problem that is being discussed here?

**Comment by mikeselander** [comment]
We already have both group fields and columns so I'm going to close out this feature now.
