### ISSUE TITLE
Hide/Show Meta-Boxes based on another form field (Feature Request)

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#161]
- Often there's scenario where post would have custom meta-boxes based on type/value
- Most details of post will be common but few details differ based on parameter
- Example: Slider post type can have simple image/text  or custom content (Image/text/buttons)
- So Slider can be of 2 types "simple Image" or "Rich Content Slide"
- Having 3 different meta boxes general details, image details, content details
- general details having dropdown type which on selection toggle visibility of meta boxes
- This can be achieved with some Javascript/jQuery Coding manually (Have implemented something on client project).
- Having something like this inbuilt would be helpful
- Will try my hand's on the code to see if i can contribute something

**Comment by duablellc** [comment]
@Cammoy, can you share the code you used for this?

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
