### ISSUE TITLE
Image uploads and file uploads

### ISSUE THREAD

**Issue by eirichmond** [humanmade/Custom-Meta-Boxes#163]
I've baked a solution into the thumbnail view of the 150px x 150px Image uploads and file uploads.
Although you can delete the upload there is no way to see a bigger version or a quick link to edit the image and I needed it for a client project I'm currently working on. So I've currently got it running with fancybox as a quick view of the larger file.
I'm happy to make a pull request and adapt it with the core thickbox and make a commit if it's worth doing so?
![screen shot 2014-02-19 at 12 29 58](https://f.cloud.github.com/assets/525490/2206437/a0f486b8-9961-11e3-8b36-33809fb12bda.png)

**Comment by mikeselander** [comment]
This can effectively be achieved by simply changing the size of the preview image so closing this out as wontfix.
