### ISSUE TITLE
Date field - select dateformat

### ISSUE THREAD

**Issue by tormjens** [humanmade/Custom-Meta-Boxes#175]
A nice feature to have would be the ability to set a dateformat as part of the arguments for a date field. In datepicker you can set it in the options-object:

```
{
dateFormat: 'DD-MM-YYYY'
}
```

This is great for plugins that have different languages. For instance, in Norway the date format should be "DD/MM/YYYY", not "MM/DD/YYYY" which seems to be the standard for some countries. 

It could be used like this:

```
array( 
'id' => 'field-18', 
'name' => 'Date input field', 
'type' => 'date', 
'format' => 'DD/MM/YYYY'
)
```

Otherwise, I love this library :-)

**Comment by richplane** [comment]
While we're waiting for this to be merged into a CMB release, here's a plugin we use to add a UK-style date field (dd/mm/yyyy): https://github.com/castlegateit/cgit-wp-cmb-ukdate

**Comment by davetgreen** [comment]
Ahh yes, this would extremely useful! :+1:

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
