### ISSUE TITLE
Tutorial article

### ISSUE THREAD

**Issue by paaljoachim** [humanmade/Custom-Meta-Boxes#188]
Hey

Bridging the gap between designer and developer. I am calling from the edge of the designer cliff asking for a rope bridge to be created, so I can bridge the gap between being a designer and developer.

One way is that somebody creates an article showing how they have used Custom Meta Boxes step for step with code examples and screenshots. Showing how powerful this actually is.

Another is that someone clicks the record button in Camstudio/Screenflow while building something useful with the Custom Meta Boxes.

When I "get it" and if I find it really useful which I probably will then I would also like to share my discoveries here: http://easywebdesigntutorials.com/ 

Ps I noticed the Wiki, but need more handholding to grasp the concept.

**Comment by mikeselander** [comment]
We've increased the documentation around individual fields in the Wiki so I'm going to close this now.
