### ISSUE TITLE
Add Group label

### ISSUE THREAD

**Issue by stompweb** [humanmade/Custom-Meta-Boxes#195]
When adding a repeatable group there are two buttons - 'Add New Group' and 'Remove Group'

For the user, it's not always going to be a 'group' so either remove that term or allow for a string to be passed through to define your own.

```php

array( 
    'id' => 'gp', 
    'type' => 'group', 
    'group_label' => 'Document',
    'repeatable' => true,
    'sortable' => true,
    'fields' => $group_fields
)
```

So in the example above it would say 'Add New Document' and 'Remove Document'.

**Comment by mikeselander** [comment]
This is available to modify with the options:

```
'string-repeat-field' => 'My New Stuff',
'string-delete-field' => 'Delete Stuff',
```

I have updated the documentation appropriately.
