### ISSUE TITLE
field-wysiwyg is have issue

### ISSUE THREAD

**Issue by smpdesignmedia** [humanmade/Custom-Meta-Boxes#204]
when we upload image in "wysiwyg" editor of metabox in "page" post type, it places the img src code in wordpress default editor

**Comment by ajitbohra** [comment]
@willmot @mattheu tested this with latest version of wordpress and CMB, its working fine with pages. We can close this issue.

**Comment by mikeselander** [comment]
Thanks Ajit, closing now.
