### ISSUE TITLE
Tabbed Groups

### ISSUE THREAD

**Issue by aijazsiddique** [humanmade/Custom-Meta-Boxes#207]
![21](https://cloud.githubusercontent.com/assets/4633863/3041397/2ce236f0-e0f4-11e3-8efc-5eb600bc33ec.PNG)

https://cloud.githubusercontent.com/assets/4633863/3041397/2ce236f0-e0f4-11e3-8efc-5eb600bc33ec.PNG

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
