### ISSUE TITLE
Allow CMB to work alongside the original Custom Metaboxes and Fields plugin

### ISSUE THREAD

**Issue by mathetos** [humanmade/Custom-Meta-Boxes#209]
I'm using this for a plugin and it's incredible. But now I notice that I get the following error if I activate my plugin after another plugin that uses either this or WebDevStudios version CMB:

```
Fatal error: Cannot redeclare class CMB_Meta_Box in C:..\wp-content\plugins\myplugin\includes\humanmade\class.cmb-meta-box.php on line 6
```

Here's a Gist of my metabox generation file:
https://gist.github.com/mathetos/6afea95a5a39048f2401

Should I be extending the class rather than just doing a filter? If so, how exactly? I tried doing that but couldn't get the contructor correct.

**Comment by mikeselander** [comment]
This would require a complete breaking-rewrite and the original plugin is unlikely to be used on any maintained production sites so I'm going to close this as wontfix.
