### ISSUE TITLE
CMB Anywhere not saving on options page

### ISSUE THREAD

**Issue by ostroso** [humanmade/Custom-Meta-Boxes#222]
When saving the options on a option page created with the filter 'cmb_options_pages' (as in example-functions.php) it won't save the fields. Instead, it gives the following notice:

NOTICE: wp-content/plugins/Custom-Meta-Boxes/class.cmb-option.php:52 - Undefined property: CMB_Options::$object_id

Can't figure out what is the problem, it works on post, pages and custom post types. It also works on 'cmb_user_meta' filter

**Comment by mikeselander** [comment]
I doubt we'll continue with the fields anywhere branch as it is - I think we can use a lot of the pieces from it but probably not as is. I'm going to close this issue since it's directly tied to the `fields-anywhere` branch.
