### ISSUE TITLE
CSS/JS files not loaded

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#226]
- Using latest version of Wordpress & CMB
- JS & CSS not loaded (Improper URL rendered)
- meta boxes class is loaded from subfolder in theme ("~THEMEROOT/inc/vendors/meta")
- Complete setup on local WAMP
- Attaching Screenshot console error
  ![cmb_error](https://cloud.githubusercontent.com/assets/1039236/3524241/1cd78412-0765-11e4-90a4-0ef99bdf5615.jpg)

**Comment by ardian-c** [comment]
had to change CMB_URL in order to make it work inside theme folder.

define('CMB_URL', get_template_directory_uri().'/inc/metaboxes/');

Is there any better solution to this issue ?

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
