### ISSUE TITLE
Flexible Content Type

### ISSUE THREAD

**Issue by braznaavtrav** [humanmade/Custom-Meta-Boxes#228]
It doesn't seem like it is currently possible, but it would be a really nice enhancement to support any content type in a single repeatable metabox. Kind of like [ACF's Flexible Content Field](http://www.advancedcustomfields.com/add-ons/flexible-content-field/). Are their any plans to support this type of functionality in the future?

**Comment by mikeselander** [comment]
There are no plans to explicitly support this in the roadmap so I'm going to close this out. 

https://github.com/CMB2/CMB2 does allow you to pass multiple post types to the field registration array so might be worth checking out.
