### ISSUE TITLE
Add 'required' concept to a field

### ISSUE THREAD

**Issue by dashaluna** [humanmade/Custom-Meta-Boxes#255]

**Comment by richplane** [comment]
+1. Quite an omission!

**Comment by dt10111** [comment]
Would like to see this also.

**Comment by mikeselander** [comment]
:+1: this to bump up priority

**Comment by mikeselander** [comment]
This ticket is tied closely with #283  and both could probably be handled together.

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
