### ISSUE TITLE
Add 'Edit' link for posts in repeatable post_select field

### ISSUE THREAD

**Issue by dashaluna** [humanmade/Custom-Meta-Boxes#256]
In repeatable post_select field, you can add multiple posts. To the far right of each post there is a cross button to delete that post. It would be handy to add an edit link next to it, so it's easy to go off and edit that post if required.
![cmb - add edit link](https://cloud.githubusercontent.com/assets/2185972/4247778/e6675e84-3a5e-11e4-83e0-c9d38ec2d1e3.png)

**Comment by mikeselander** [comment]
This is no longer on the roadmap. Closing.
