### ISSUE TITLE
change metabox page template wise

### ISSUE THREAD

**Issue by smpdesignmedia** [humanmade/Custom-Meta-Boxes#263]
want about to add functionality for changing metabox options when we change page template.

- do you have idea about it, i want to change metabox option on page template selection, to create a contact page template

**Comment by sanchothefat** [comment]
@smpdesignmedia current you can do this but the metaboxes only become visible after saving the post / page.

See the `show_on` option here: https://github.com/humanmade/Custom-Meta-Boxes/wiki/Create-a-Meta-Box

eg

```php
$fields = array(
    'title' => 'Contact form fields',
    'show_on' => array( 'page-template' => array( 'page-contact-form.php' ) ),
    'fields' => array( ... )
);
```

**Comment by igregson** [comment]
In case it's helpful for anyone, here's one take on the js approach mentioned by @Cammoy

```
jQuery(document).ready(function($) {

  var templateSelect   = $('#page_template')   // Template dropdown select box (native WP id)
  var metabox             = $('#name-of-metabox-to-show-and-hide')
  var template             = 'template-to-show-and-hide-file-name.php'

  templateSelect.change(function() {
    if ( $(this).val() === template ) {
      metabox.show()
    } else {
      metabox.hide()
    }
  }).change()

})
```

**Comment by mikeselander** [comment]
Closing as solved with the JS above.
