### ISSUE TITLE
Is there a v1.0.2 tag to download stable?

### ISSUE THREAD

**Issue by cliffordp** [humanmade/Custom-Meta-Boxes#264]
Tags screenshot:
![screen shot 2014-09-16 at 6 54 30 am](https://cloud.githubusercontent.com/assets/1812179/4286684/57ae241a-3d98-11e4-94fa-4cf3a27c3222.png)

Or Releases: https://github.com/humanmade/Custom-Meta-Boxes/releases

**Comment by JustinBusschau** [comment]
Any movement on this? Are we still to use 1.0.1? Is 1.0.2 ready yet?

**Comment by mikeselander** [comment]
1.0.2 has been tagged and released.
