### ISSUE TITLE
Pass Media (Image) URL to WP-API JSON File

### ISSUE THREAD

**Issue by joedajigalo** [humanmade/Custom-Meta-Boxes#267]
Is there a way/setting to pass the Media (ie. image) URL instead of the ID?

I am using the WP-API plugin - to get the custom meta data, and it's passing the media ID, instead of the URL.

Repeatable image field, retrieving image ID:
`cmb_image_gallery":["8","6"]`

Thanks,
Joe.
- Edit, maybe this may be a question more for WP-API instead of Custom Meta Boxes

**Comment by mikeselander** [comment]
As Ryan pointed out in the WP-API ticket that was opened for this ticket, this can be easily modified by filtering the output for the endpoint so I'm going to close this out.
