### ISSUE TITLE
Hitting 'enter' brings up 'are you sure you want to delete this field' dialog

### ISSUE THREAD

**Issue by dougcassidy** [humanmade/Custom-Meta-Boxes#270]
If you fill out a field (CMB or standard WP) and hit 'enter' (like I do, often, to publish) you will get the dialog  'are you sure you want to delete this field', as if you are about to delete a repeating field.

And if you do have repeating fields, it will delete the first one of them if you say OK.

**Comment by mikeselander** [comment]
@dougcassidy - I tried replicating this and could not. Since this is so old, I am going to close it for now. If you happen to still have a more specific example that we can work off of to replicate please re-open this and @ ping me!
