### ISSUE TITLE
Conflict with Download Monitor

### ISSUE THREAD

**Issue by cehwitham** [humanmade/Custom-Meta-Boxes#271]
When using this as a MU Plugin, with all other plugins disabled there is a conflict that causes duplicate title bars on the Add Download thickbox.

![screen shot 2014-10-28 at 09 42 33](https://cloud.githubusercontent.com/assets/2518941/4806620/1d738844-5e8b-11e4-8316-2ec94f0cd5ab.png)

The title seems to be repeated for every set of metaboxes that are added to the page so if there are a lot of metabox sections on a page, the title might output 6/7 times and forces the "Insert Download" button out of the thickbox so you can't click on it.

I've tried to identify which Scripts are causing the issue but I haven't managed to find one yet.

https://wordpress.org/plugins/download-monitor/

**Comment by mikeselander** [comment]
Closing as versions of both plugins have changed dramatically since posting so tracking this down will be nigh-impossible.
