### ISSUE TITLE
Trim values on save

### ISSUE THREAD

**Issue by pdewouters** [humanmade/Custom-Meta-Boxes#274]
Right now if I enter only spaces into a field, it is saved as is. Maybe we should trim the value before saving?

**Comment by vodou** [comment]
Is there a filter or an action where I can accomplish this? I'm sorting based on last names, and the ones of the form ` Lastname` are of course showing up higher than `Lastname`.

**Comment by barryceelen** [comment]
When saving post meta the `update_metadata()` function is used. This has a filter `update_{$meta_type}_metadata` you can use to do stuff to your post meta before it get saved to the database.

**Comment by vodou** [comment]
That seems to only determine whether or not to update the metadata.
From the code:
```
/**
     * Filter whether to update metadata of a specific type.
     *
     * The dynamic portion of the hook, `$meta_type`, refers to the meta
     * object type (comment, post, or user). Returning a non-null value
     * will effectively short-circuit the function.
```
Still looking.

**Comment by barryceelen** [comment]
@vodou Ah yes you are correct. Right before that filter is applied, the meta value is run through `sanitize_meta()`. This is where you could trim your value.

`$meta_value = sanitize_meta( $meta_key, $meta_value, $meta_type );`

**Comment by vodou** [comment]
@barryceelen That looks more like what I was trying to find. (Not sure how I missed it, but I did.) Thanks!

**Comment by vodou** [comment]
Just for completeness' sake, here's what ended up being the solution (for me, anyways):

```
// Sanitize the first_name and last_name metadata 
$meta_fields = array( 'username', 'first_name', 'last_name' );
foreach( $meta_fields as $mf ) {
	$meta_key = self::PREFIX . $mf;
	add_filter( "sanitize_post_meta_{$meta_key}", function( $meta_value ) {
		return trim( $meta_value );
	} );
}
```

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
