### ISSUE TITLE
Inserting / Updating Repeatable field from frontend

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#279]
Working on small project using Custom Metaboxes and would like to insert & update repeatable custom field from frontend.

**Comment by mikeselander** [comment]
This is possible but will need to be handled by your own front end form.

**Comment by ajitbohra** [comment]
@mikeselander i guess we implemented above will check and get sample code added to Doc for reference

**Comment by mikeselander** [comment]
I appreciate it Ajit!
