### ISSUE TITLE
Date fields width

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#281]
- Date Type field not taking the whole width
- Currently it uses class ".cmb_text_small" which is overriding 100% width

![meta_datefield](https://cloud.githubusercontent.com/assets/1039236/5226149/8e47e9c2-7711-11e4-9fbc-d29f39b3faf8.png)

**Comment by mikeselander** [comment]
I agree that this should stretch the whole width if a column count is assigned. Adding to next major release.

**Comment by ajitbohra** [comment]
@mikeselander we can label this as "Has PR" and close the issue.

**Comment by mikeselander** [comment]
Labeled Has PR but the issue will auto-close when the PR is merged 👍
