### ISSUE TITLE
Group Field Customizable Button Text

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#282]
It would be good to have a parameter to set Group field button text instead of generic "Add New Group "
![group_button](https://cloud.githubusercontent.com/assets/1039236/5226463/f6e576a4-7714-11e4-9296-20656aba01cf.png)

**Comment by fruitpixel** [comment]
You can use the (not yet release) filter as suggested by tareiking, or you can already do this using the parameters 'string-repeat-field' & 'string-delete-field' to override the 'Add New Group' & 'Remove Group' respectively : 

```
array( 
    'id'   => 'example-group', 
    'name' => 'A Group', 
    'type' => 'group',
    'fields' => $fields, // An array of fields. 
    'string-repeat-field' => 'Add New',            
    'string-delete-field' => 'Remove'
),
```

**Comment by davetgreen** [comment]
Love the undocumented parameters. Not being able to re-label the buttons has always bugged me, but I'm glad I came looking for a solution now! 

Happy to submit a PR to update the docs :+1:

**Comment by ajitbohra** [comment]
@rikanio thanks for this awesome args info loved it:) didn't knew about it. @davetgreen parameters info added to wiki/documentation.
