### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#283]
Hello everyone,
- Planning to work on custom meta validation 
- Would like to know what approach should we take, validation using HTML5 / CSS3 or using jQuery validation plugins
- How validation messages should be handled "inline, floating etc" 

Kindly provide suggestions so we can plan and implement that.

**Comment by mikeselander** [comment]
@AlchemyUnited would like to continue the discussion on this - you said you had a working model for validation in the backend. Are you still working on this?

**Comment by mattheu** [comment]
I'd like to have both sanitization and validation callbacks as options when you add a field. We could have some sensible defaults too for fields such as 'number'.

I really like how the rest API infrastructure handles this.  See https://developer.wordpress.org/reference/functions/register_rest_route/

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
