### ISSUE TITLE
Metadata is duplicated in not-repeatable field

### ISSUE THREAD

**Issue by hadoanngoc** [humanmade/Custom-Meta-Boxes#284]
When I import data of a custom post type, metadata is duplicated in not-repeatable field. Probably there are orphan metadatas that cause this.

In class.cmb-meta-box.php, line 48 (latest version), there are these lines:

// If we are on a post edit screen - get metadata value of the field for this post
			if ( $post_id ) {
				$values = (array) get_post_meta( $post_id, $field['id'], false );
			}

![2014-12-04_150259](https://cloud.githubusercontent.com/assets/2139305/5295249/a4587f2e-7bc6-11e4-8546-fd3daf92b40a.jpg)

I fixed by editing into this 

if ( $post_id ) {
				if($field['repeatable'] == true){
					$values = (array) get_post_meta( $post_id, $field['id'], false );
				} else {
					$values = get_post_meta( $post_id, $field['id'], true );
				}
}

Does anyone agree?

**Comment by mikeselander** [comment]
Seems verified by multiple votes - will address in next minor release.
