### ISSUE TITLE
too many fields not saving

### ISSUE THREAD

**Issue by Nick-SL** [humanmade/Custom-Meta-Boxes#285]
I have a “product” cpt, and another post type, “plants”, with some custom taxonomies.
I create a cmb with groups of fields, one group for each one of the published posts of “plants” cpt, each group contains a checkbox, two text fields, and then a variable set of text fields, depending on the terms of the custom taxonomy associated with that specific “plant” post.
The problem is that at a certain point the meta fields are not being saved.
I believe they are too many for the request, because in alphabethical order fields are saved up to groups starting with “C”, then every value inserted after that is lost.
What do you believe the problem is? And what can I do to solve it?

**Comment by mikeselander** [comment]
@Nick-SL did @evoratec's solution do the trick for you?

**Comment by Nick-SL** [comment]
@mikeselander yep that solved my issue, though I had to go through server's settings to change that value

**Comment by mikeselander** [comment]
OK thank you for confirming! I'm going to clo0se this issue for now, but will make a note to look at potential solutions that don't involve server configurations.
