### ISSUE TITLE
Custom Extension

### ISSUE THREAD

**Issue by hellofantastic** [humanmade/Custom-Meta-Boxes#291]
Looking to write our own Radio input field as an extension because we would like to be able to have a different description under each radio label... So i'm asking can I alter the radio input arguments to take multiple description fields, then in my extension html output I can arrange it how I'd like? Insight appreciated
mockup image shows what I'm after

![screen shot 2015-02-08 at 8 55 06 am](https://cloud.githubusercontent.com/assets/6655746/6097355/45b2d950-af70-11e4-8939-79108854055a.png)

**Comment by mattheu** [comment]
The plugin is designed for easily creating your own custom extensions.

Here is some documentation: https://github.com/humanmade/Custom-Meta-Boxes/wiki/Adding-your-own-field-types

I would probably reccommend creating one that extends the radio field types, and provides a custom 'html' method that can output your markup. You can pass any extra data needed to the field when registering it.

**Comment by hellofantastic** [comment]
okay I am following, looking at the classes.fields.php , and the wiki add own field types , is this the registering part 
```
add_filter( 'cmb_field_types', function( $cmb_field_types ) {
    $cmb_field_types['custom_radio'] = 'Custom_Radio';
    return $cmb_field_types;
} );
```

which would go in functions.php and then my custom field class file would sit in same folder as classes.fields.php

then to pass extra data I just do it in the fields array?

array( 'id' => 'custom-radio', 'name' => 'Image or Video for Slider', 'type' => 'radio', 'options' => array(  'image' => 'Image',  'video' => 'Video',  'both' => 'Both' ), 'desc'=>'', desc2='blah blah', desc3='balh balh'),


 or in this part

```
add_filter( 'cmb_field_types', function( $cmb_field_types ) {
    $cmb_field_types['custom_radio'] = 'Custom_Radio';
    return $cmb_field_types;
} );
```

**Comment by hellofantastic** [comment]
Looking at this [GitHub](https://github.com/humanmade/Custom-Meta-Boxes/issues/157)

is seems some things are missing from the wiki.
So you add custom class to classes.fields.php
And add an entry to "custom-meta-boxes.php" _cmb_available_fields array

I assume those files are not over written in an update?

**Comment by mattheu** [comment]
I would reccommend adding everything to a new file - either included in your theme or  as a plugin. This will prevent anything getting overwritten when updating.

You first need to filter the available field types and add your own - specifying the class used.

Then you can create your class - which extends CMB_Radio_Field

Don't worry about adding anything to "custom-meta-boxes.php"- this is what the filter does.

**Comment by hellofantastic** [comment]
Ah okay got it..magic ....
Well all is done on what I'm working on how do I give back?

**Comment by mattheu** [comment]
Glad to hear you got it working. By all means contribute back anything useful you do - but don't feel you need to! :smile: Perhaps you can use your experiences to make some suggestions on improving the documentation for creating custom fields?

**Comment by hellofantastic** [comment]
OKay 

would suggestion go under new issue?

Also i realized when I'm in the git issue area I can chime in on folks who need help.

On 2015-02-10, at 10:15 AM, Matthew Haines-Young wrote:

Glad to hear you got it working. By all means contribute back anything useful you do - but don't feel you need to!  Perhaps you can use your experiences to make some suggestions on improving the documentation for creating custom fields?

—
Reply to this email directly or view it on GitHub.


Dallas Larsen
Principal at hellofantastic
dallas@hellofantastic.com
250.509.0036
www.hellofantastic.com

**Comment by mattheu** [comment]
Yes please- create a new issue for suggestions
