### ISSUE TITLE
issue with select field

### ISSUE THREAD

**Issue by smpdesignmedia** [humanmade/Custom-Meta-Boxes#294]
( ! ) Notice: Undefined index: allow_none in "wp-content\plugins\Custom-Meta-Boxes-master\classes.fields.php" on line 1090

 i found this issue in all of the custom metabox fields.

- this error comes when there is a debug mode on.

**Comment by jahir07** [comment]
$this->args['allow_none'] = '';
add this line, before 1090 line

**Comment by mattheu** [comment]
Fixed in https://github.com/humanmade/Custom-Meta-Boxes/pull/302
