### ISSUE TITLE
double double metabox item, after import/export of sample data in wordpress

### ISSUE THREAD

**Issue by smpdesignmedia** [humanmade/Custom-Meta-Boxes#295]
- i found double double metabox item after import/export data.

- please, can you see the screenshot for this issue ?

![untitled](https://cloud.githubusercontent.com/assets/5764334/6511370/72cc2c3a-c392-11e4-9e2c-8e3d8f075662.png)

**Comment by devariya** [comment]
I also found same problem

**Comment by mikeselander** [comment]
Closing as duplicate of #284
