### ISSUE TITLE
metaboxes on user profile page ?

### ISSUE THREAD

**Issue by ardian-c** [humanmade/Custom-Meta-Boxes#300]
Hi, I have been trying to make metaboxes to appear in users page with no result.
The official 'pages' => array('user') does not yield any content in users profile page. Have been reading through documentation but I haven't find solution, any ideas ?

Here is a part from code used to for metaboxes.

 $meta_boxes['user_meta_profile'] = array(
            'id'        => 'user_meta_profile',
            'title'     => __('User Profile Informations', 'cmb'),
            'pages'     => 'user',
            'fields'    => array(
                array(
                    'name'  => 'Picture',
                    'id'    => $prefix.'_user_picture',
                    'type'  => 'file',
                    'preview_size' => array(120, 120)
                ));

**Comment by podlebar** [comment]
well.. i guess this is not possible.. 
you can define with 'pages' if it should show up on a post or page.. or any custom posttype. (or a id of a page or post)

The 'pages' parameter is a bit misleading in this case. Should be called 'posttypes' or so.

you could give https://github.com/WebDevStudios/CMB2 a try if you want this functionality but i think this plugin is more 'stable' currently.

**Comment by ardian-c** [comment]
hmm thnx podlebar, I have been searching all over to get this working with no results. I think I need to do this manually without switching to CMB2. Any plans to add this feature in newer versions ?

**Comment by podlebar** [comment]
i'm not a dev of this project so i don't know.. sorry

**Comment by mattheu** [comment]
I'd love to support this feature, and I have looked into it.

Realistically -  I don't have time to implement this at the moment. Its not off the cards, but unless I have a project that requires it - I probably won't get to it soon.

**Comment by podlebar** [comment]
a basic implementation of http://parsleyjs.org/ would be possible without "much" work..
will try it

**Comment by mikeselander** [comment]
This is a very cool feature, but not something that we're looking to support. 

https://github.com/CMB2/CMB2 does support metaboxes on user profile pages and would be worth looking into.
