### ISSUE TITLE
Notice: Undefined index: \class.cmb-meta-box.php on line 52

### ISSUE THREAD

**Issue by jahir07** [humanmade/Custom-Meta-Boxes#303]
how to fix this issue?

**Comment by mikeselander** [comment]
@jahir07 I know this was submitted quite a while ago but are you still experiencing this issue? If so, this line doesn't correspond with code that would trigger this error on the current `master` so could you please  include the line in your version triggering this issue?

**Comment by mikeselander** [comment]
Jahirul, I'm going to close this issue for now as it's quite stale. If you have more information for us, please re-open this and @ ping me!
