### ISSUE TITLE
shortcode support

### ISSUE THREAD

**Issue by alanzucker** [humanmade/Custom-Meta-Boxes#312]
Are shortcodes supported within the WYSIWYG field in CMB?  Is there a way to enable them?  We would like to be able to use codes such as the [audio] shortcode.

**Comment by alanzucker** [comment]
Figured this out.  Need to wrap field output with do_shortcode().

**Comment by mattheu** [comment]
Yeah - often worth applying the_content filters to the output of the WYSIWYG. There's a few things eg `wp_autop` that you need to do too.
