### ISSUE TITLE
Composer install failed

### ISSUE THREAD

**Issue by TweetPressFr** [humanmade/Custom-Meta-Boxes#314]
Hi,

I'd like to use your framework as dependancy for my WP plugin but it seems impossible, I get this error : 

"The requested package humanmade/custom-meta-boxes could not be found in any version, there may be a typo in the package name."

Is it something known ? Did I miss something in my composer.json ? I did not find any typo.

**Comment by diggy** [comment]
Looks like it's not available through packagist? https://packagist.org/search/?q=humanmade

@TweetPressFr you can get the package like e.g.:

```
{
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/humanmade/Custom-Meta-Boxes"
    }
  ],
  "require": {
    "humanmade/custom-meta-boxes": "dev-master"
  }
}
```

**Comment by mikeselander** [comment]
It looks like this requires adding HMCMB to Packagist which is not currently something that we're interested in supporting. Closing this out as wontfix.
