### ISSUE TITLE
Add sanitize_callback to default arguments

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/Custom-Meta-Boxes#321]
Including a sanitization callback in the default arguments would be handy.

Notes/random thoughts:
- Run inside the $value loop of the save function
- accepts one argument only
- if not a callback, a filter with the arguments:
  - $value
  - $type
  - $id
  - $post_id

Related #269
CC @mattheu, as discussed in another project.

**Comment by mattheu** [comment]
I'd love for this to be mandatory but don't think we really can for backwards compatibility reasons.

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
