### ISSUE TITLE
Repeater problem in latest wordpress version 4.5.1

### ISSUE THREAD

**Issue by shankhadevpadam** [humanmade/Custom-Meta-Boxes#322]
The repeater function is not worked in the latest WordPress version.

**Comment by pdewouters** [comment]
What is the issue exactly that you encounter? Any error messages?

**Comment by mikeselander** [comment]
@shankhadevpadam do you have more info on this that we can use to track it down?

**Comment by mikeselander** [comment]
Closing this as stale - Padam, please re-open if you have more info to share with us 👍
