### ISSUE TITLE
Add show_titles option to field groups

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#324]
Would like to add the option to hide title on fields for a cleaner interface.

For example: `'show_name' => false` would result in the field name not displaying as a label above the field. We could easily make it still available to screen readers by using a typical screen-reader only class.

Thoughts? @mattheu @joehoyle

**Comment by fedeescalada** [comment]
+1

**Comment by mikeselander** [comment]
This is a nice feature, but no longer on our roadmap. I'm closing this out as wontfix.
