### ISSUE TITLE
Consider support for register_meta()

### ISSUE THREAD

**Issue by johnbillion** [humanmade/Custom-Meta-Boxes#325]
[WordPress 4.6 introduces a fundamental change to the way meta fields are registered.](https://make.wordpress.org/core/2016/07/08/enhancing-register_meta-in-4-6/) The primary change is the addition of meta metadata such as its type, description, value structure, and whether to expose it in the REST API.

We should consider whether registered CMB meta fields should also call `register_meta()` in order to expose meta fields to this new meta API.

**Comment by eirichmond** [comment]
Is there any consideration for this yet to coincide with the upcoming release of the new REST API?

**Comment by mikeselander** [comment]
@eirichmond no, there's no consideration for this as of yet, but I'm tagging it for 1.2.

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
