### ISSUE TITLE
Allow omitting id field attribute and format from name

### ISSUE THREAD

**Issue by shadyvb** [humanmade/Custom-Meta-Boxes#333]
It'd be helpful if one can specify either `id` or `name` of the field and get the other formatted from the defined.

ie:
`[ 'id' => 'foo-bar' ]` would be transformed to `[ 'id' => 'foo-bar', 'name' => 'Foo Bar' ]`
`[ 'name' => 'Foo Bar' ]` would be transformed to `[ 'id' => 'foo-bar', 'name' => 'Foo Bar' ]`

Just like what happens in `extended-taxos` [here](https://github.com/johnbillion/extended-taxos/blob/master/extended-taxos.php#L156).

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
