### ISSUE TITLE
Default page template can be empty string or ‘default'

### ISSUE THREAD

**Issue by barryceelen** [humanmade/Custom-Meta-Boxes#347]
To show a meta box on a page with the ‘default’ template selected (or no template selected) you currently have to do this:

`'page-template' => array( '', 'default’ )`

Would be nice if the plugin would handle this.
On a side note, it would be better to check for the current page template by using `get_page_template_slug( $post_id )` in stead if `get_post_meta( $post_id, '_wp_page_template', true )`. The former always returns an empty string if the ‘default’ template or no template is chosen.

Kind of related: #305

**Comment by swissspidy** [comment]
`get_page_template_slug()` makes sense and there won't be any post type check anymore in WordPress 4.7

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
