### ISSUE TITLE
TODO(Working): Documentation Improvement

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#354]
@mattheu @mikeselander Creating this todo list here will work on this:
1. <del>Homepage "misc optional args" link missing</del>
2. <del>Homepage "colour picker" link missing</del>
3. <del>Colour picker page "screenshot" missing</del>
4. <del>Code field adding "rows" args</del>
5. <del>Homepage" number field" missing</del>
6. <del>Number field "Screenshot" missing</del>
7. <del>Colour field missing in sidebar</del>

### **<del>Logical Grouping of Field Types as below;</del>**
**Can we group fields on wiki page ?** 
_**General:**_
- Text
- Small Text
- Number
- URL
- Textarea
- Code
- Select
- Checkbox
- Radio

**_Data & Time:_**
- Date
- Time
- Date (Unix)
- Date & Time (Unix)

**_Wordpress:_**
- Taxonomy Select
- Post Select

**_Media:_**
- File Upload
- Image Upload

**_Utilities:_**
- Title
- WYSIWYG
- Group
- Location - Google Map
- Colour Picker

**Comment by ajitbohra** [comment]
@mikeselander i am done with documentation changes listed here. Feel free to keep it open for discussion.

**Comment by mikeselander** [comment]
OK @ajitbohra I'll go ahead and close this one then. Thanks for your contributions!
