### ISSUE TITLE
Improve inline documentation

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#361]
After I'm all done with #360 I'd like to spend some time on improving inline documentation - will be helpful with contributors in the future and make the project easier to extend.

**Comment by ajitbohra** [comment]
@mikeselander Inline documentation ?

**Comment by mikeselander** [comment]
@ajitbohra yes - doc blocks, single-line comments and any supporting documentation in the code itself. It helps with making changes and future maintainability.

**Comment by ajitbohra** [comment]
Cool thanks for the explanation :) let me know if can help you on that

**Comment by mikeselander** [comment]
This was more or less achieved in #374. Closing.
