### ISSUE TITLE
Information: CMB Sublime Snippets

### ISSUE THREAD

**Issue by ajitbohra** [humanmade/Custom-Meta-Boxes#365]
![Sublime Snippets](https://cloud.githubusercontent.com/assets/1039236/19284518/ce8d1760-9013-11e6-9d01-6a6c721af758.gif)

# CMB Sublime Snippets
[https://github.com/lubusonline/CMB-sublime-snippets](https://github.com/lubusonline/CMB-sublime-snippets)

HumanMade's Custom Meta Box is an important part of my wordpress development workflow. Extensively use it on majority of projects to craft beautiful custom back ends which are easy to use. To speed up workflow created these sublime snippets. Recently updated snippets to be inline with latest CMB and thought to share it with other fellow developers. Will actively keep improving it.

**Comment by mikeselander** [comment]
Very cool @ajitbohra! I see you've added this to the Wiki so I'm going to close this issue out for now since people can find this there.
