### ISSUE TITLE
Maps metabox shows 3 instances on saving.

### ISSUE THREAD

**Issue by invmatt** [humanmade/Custom-Meta-Boxes#367]
Initially the map metabox displays correctly and the correct value is being stored in the database:

```a:3{s:3:"lat";s:18:"53.800755400000014";s:4:"long";s:19:"-1.5488950097869747";s:9:"elevation";s:17:"49.35803604125977";}```

However once you've clicked update 3 instances of the map are being loaded, all of which show the incorrect value.

<img width="1253" alt="screen shot 2016-11-21 at 09 13 38" src="https://cloud.githubusercontent.com/assets/1536844/20476890/1a9af632-afcb-11e6-8a6f-cca7851d686f.png">

Here's the code to generate the box:

```php
<?php
  function test_google_maps(array $meta_boxes) {
    $fields = array(
      array( 'id' => 'testing_google_map', 'name' => 'Location', 'type' => 'gmap', 'google_api_key' => get_option('test_gmaps_key') ),
    );

    $meta_boxes[] = array(
      'title' => 'Google Map',
      'pages' => 'page',
      'fields' => $fields,
      'show_on' => array( 'page-template' => array( 'template-home.php' ) ),
    );

    return $meta_boxes;
  }

  add_filter( 'cmb_meta_boxes', 'test_google_maps' );
?>
```

**Comment by mikeselander** [comment]
Hey @invmatt thanks for reporting this - I've been able to replicate it and we'll probably look to fix this in a 1.1 release. Sorry for the hassle!
