### ISSUE TITLE
Add email field type

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#372]
Or, make validation of email possible with an attribute on the text field. Open to opinions on this one.

**Comment by barryceelen** [comment]
A field with `type="email"` would show an appropriate keyboard on devices with an on-screen keyboard. Optional validation via a `novalidate` attribute, or validation eg. via `is_email()` would be useful.

I’d think an additional email field in stead of adding an option to the text field would be a better implementation.
