### ISSUE TITLE
Add user field

### ISSUE THREAD

**Issue by rmccue** [humanmade/Custom-Meta-Boxes#400]
It'd be great to allow selecting a user.

**Comment by ajitbohra** [comment]
@rmccue select field for users like we have for post right ?

**Comment by rmccue** [comment]
Yup, with the same Select2 magic. :)

**Comment by ajitbohra** [comment]
@rmccue sounds good was just wondering we have author field on post/page !

**Comment by mikeselander** [comment]
Closing this issue as we will not be pursuing enhancements.
