### ISSUE TITLE
Bump required minimum PHP to 5.4

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#403]
`> PHP5.4` now has more then 75% usage in the WP ecosystem and since this is a developer tool Ryan has recommended bumping the minimum support to 5.4. I agree and would love to stop writing long-form array syntax.

If there are any objections or serious issues with this please post here. Otherwise this will happen with 1.1.

**Comment by tareiking** [comment]
No objection, just praise! So be it sir.

**Comment by mikeselander** [comment]
I see no objections so it's happening 🎉
