### ISSUE TITLE
CMBData is output repeatedly

### ISSUE THREAD

**Issue by rmccue** [humanmade/Custom-Meta-Boxes#411]
<img width="775" alt="screenshot 2017-02-22 11 10 01" src="https://cloud.githubusercontent.com/assets/21655/23193207/76e39aae-f8f3-11e6-9c36-571582b13f2b.png">

**Comment by mikeselander** [comment]
Hey @rmccue or @tareiking I can't replicate this locally, could you give me some more context on the fieldset and/or amount of data causing this? Like, is it a ton of individual or repeated WYSIWYG fields making this?

**Comment by mikeselander** [comment]
As an update, this is looking like a core issue to me. Core allows you to re-register the same `localize` variable over and over again without any checks whether it's already been registered already. I see no easy way to see if we've already registered this script as localized but will keep digging over time.

**Comment by barryceelen** [comment]
A workaround might be to check if `cmb-scripts` is already enqueued  with [`wp_script_is()`](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/functions.wp-scripts.php#L311) before adding the action in the `CMB_Meta_Box` construct method or inside `enqueue_scripts()` method.

```
if ( ! wp_script_is( 'cmb-scripts' ) ) {
	// Enqueue and/or localize 'cmb-scripts'.
}
```
