### ISSUE TITLE
Google Maps not working well in the back end

### ISSUE THREAD

**Issue by verytwisty** [humanmade/Custom-Meta-Boxes#417]
The google map appears fine on the front end of the site, but the back end looks very odd.

On the back end the map looks & works fine (it finds the postcode and puts the marker in the correct place) until the post is saved. Once it is saved  four maps appear instead of one, and the location goes back to the default place for all four of them. 

If the post is saved again without re-entering the post code data, the map on the front end stops working as the location data doesn't come through. 

this is my code:
array( 'id' => 'contact_map', 'name' => 'Google Map', 'type' => 'gmap', 'google_api_key' => '{correct key here}' ),

Pretty sure I've got the correct API key, got it here: https://console.developers.google.com/apis/credentials

The same problem occurs with the 'sample functions' file enabled.

![gmap](https://cloud.githubusercontent.com/assets/5609978/23470440/4c3824b8-fe9e-11e6-9c0e-584371515ff0.png)

**Comment by mikeselander** [comment]
Hi @verytwisty - this looks like an issue that we've solved recently in the `develop` branch - could you do me a favor and pull down that branch at the latest commit to test?

**Comment by verytwisty** [comment]
Hi @mikeselander Sorry I didn't see your message. I have pulled the develop branch and the map page works great now. Is this branch OK to use in production? :-)

**Comment by mikeselander** [comment]
@verytwisty I can't guarantee that it's OK to use in production yet. Most likely to be OK, but not 100% tested as-is. 

We are using it on a (large) production site now but I'm not planning to do full regression testing until we've all the features that we want for the release in the branch.
