### ISSUE TITLE
Fix Travis build for PHP7.0

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#425]
PHP 7.0 builds have mysteriously stopped working so need to fix this.

While at it, we might as well see if we can add 7.1 and remove 5.3 (#403) on the build

**Comment by tareiking** [comment]
@mikeselander this looks related : https://core.trac.wordpress.org/ticket/40086 via https://github.com/xwp/wp-dev-lib/commit/29996335751d208c4a48e10377a83db4ebc80768

**Comment by mikeselander** [comment]
Sure does, nice find!
