### ISSUE TITLE
Caminho errado de arquivos

### ISSUE THREAD

**Issue by ferrazrenato** [humanmade/Custom-Meta-Boxes#431]
Esta vindo assim:
<script type='text/javascript' src='http://127.0.0.1/visto/wp-content/plugins/C:/wamp64/www/visto/wp-content/themes/frikka/inc/Custom-Meta-Boxes/js/cmb.js?ver=4.7.4'></script>

Deveria vir assim:
<script type='text/javascript' src='http://127.0.0.1/visto/wp-content/themes/frikka/inc/Custom-Meta-Boxes/js/cmb.js?ver=4.7.4'></script>

**Comment by mikeselander** [comment]
Oi @ferrazrenato - obrigado por enviar o problema! Isso parece ser uma duplicata de #226. Eu vou fechar este bilhete em vez da edição anterior. Adicione mais detalhes a ele para que possamos rastrear tudo em um único local.
