### ISSUE TITLE
Display image loaded in metabox

### ISSUE THREAD

**Issue by ferrazrenato** [humanmade/Custom-Meta-Boxes#435]
After inserting an image field with Custom-Meta-Boxes, how do I make it to the front-end? When I return the field, the result is the image ID.

**Comment by mikeselander** [comment]
HI @ferrazrenato - we store the image ID in the meta boxes so that you have more flexibility when retrieving the image yourself. You can do it however you want this way.

To use this on the front end you could go several different ways, but a quick example would be:
```php
$image_id = get_post_meta( $my_post_id, 'my-image-meta-id', true );
// Get the URL only.
$url = wp_get_attachment_url( $image_id );
// Get a full image tag.
wp_get_attachment_image( $image_id )
```
