### ISSUE TITLE
Warning -  Failed opening

### ISSUE THREAD

**Issue by heartbreakkid58** [humanmade/Custom-Meta-Boxes#440]
I have an issue with the files, while opening website, it shows me different Warnings and all are due to "failed to open stream: No such file or directory in...."" . When I go back to my directory to check the files, they are renamed as ""class-cmb-text-field.php.suspected"". What would be the issue? Is their any infected file is in server? Also, I face this thing repeatedly twice a month, then I upload all files again.

**Comment by mikeselander** [comment]
Hi @heartbreakkid58 - this sounds to me like your host is flagging files on a security review that may or may not have been modified. We definitely do not modify our own files with a made up suffix. I would contact your host and ask them why this is happening.
